# Generated by Django 4.1.7 on 2023-05-13 07:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=6)),
                (
                    "maintenanceDate",
                    models.DateField(
                        default=datetime.datetime(2023, 5, 13, 7, 14, 6, 677210)
                    ),
                ),
                (
                    "mach",
                    models.CharField(
                        choices=[
                            ("PC", "PC - Run windows"),
                            ("Mac", "MAC - Run MacOS"),
                            (
                                "Serveur",
                                "Serveur - Simple Server to deploy virtual machines",
                            ),
                            ("Switch", "Switch - Tom maintains and connect servers "),
                        ],
                        default="PC",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "secu",
                    models.CharField(
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{13,13}$")
                        ],
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
            ],
        ),
    ]
