# Generated by Django 4.1.7 on 2023-05-14 11:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=6)),
                (
                    "maintenanceDate",
                    models.DateField(
                        default=datetime.datetime(2023, 5, 14, 11, 24, 6, 135086)
                    ),
                ),
                (
                    "mach",
                    models.CharField(
                        choices=[
                            ("PC", "Windows"),
                            ("Mac", "MacOS"),
                            ("Serveur", "Serveur"),
                            ("Switch", "Switch"),
                        ],
                        default="PC",
                        max_length=32,
                    ),
                ),
                (
                    "address_ip",
                    models.GenericIPAddressField(
                        default="0.0.0.0",
                        protocol="IPv4",
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='The IP address "0.0.0.0" can only be used as the default value',
                                regex="^(?!0\\.0\\.0\\.0$)",
                            ),
                            django.core.validators.validate_ipv4_address,
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("telephone", models.CharField(default="None", max_length=10)),
                (
                    "email",
                    models.EmailField(blank=True, default="None", max_length=254),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Homme", "Homme"),
                            ("Femme", "Femme"),
                            ("Autre", "Autre"),
                        ],
                        default="Autre",
                        max_length=32,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[("Tours", "Tours"), ("Paris", "Paris")],
                        default="Paris",
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Utilisateur", "Utilisateur"),
                            ("Administrateur", "Administrateur"),
                        ],
                        default="Utilisateur",
                        max_length=15,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="computerApp.machine",
                    ),
                ),
            ],
        ),
    ]
