# Generated by Django 4.1.7 on 2023-05-19 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="administrateur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("role", "Administrateur"), ("site", models.F("site"))
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrateur_machines",
                to="computerApp.personnel",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="personnel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machine_attitre",
                to="computerApp.personnel",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="site",
            field=models.CharField(
                choices=[("Tours", "Tours"), ("Paris", "Paris")],
                default="Paris",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 19, 19, 56, 38, 234344)
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="nom",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="genre",
            field=models.CharField(
                choices=[("Mr", "Homme"), ("Mme", "Femme"), ("", "Autre")],
                default="Autre",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="machine",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_attitre",
                to="computerApp.machine",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="site",
            field=models.CharField(
                choices=[("Tours", "Tours"), ("Paris", "Paris")],
                default="Paris",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Infrastructure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                (
                    "site",
                    models.CharField(
                        choices=[("Tours", "Tours"), ("Paris", "Paris")],
                        default="Paris",
                        max_length=15,
                    ),
                ),
                (
                    "administrateur",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("role", "Administrateur"), ("site", models.F("site"))
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administrateur_infrastructure",
                        to="computerApp.personnel",
                    ),
                ),
                (
                    "machines",
                    models.ManyToManyField(
                        blank=True,
                        related_name="infrastructures",
                        to="computerApp.machine",
                    ),
                ),
            ],
        ),
    ]
