# Generated by Django 4.1.7 on 2023-03-17 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "N_secu",
                    models.CharField(
                        default="null",
                        editable=False,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{13,13}$")
                        ],
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
            ],
        ),
    ]
