# Generated by Django 4.1.7 on 2023-06-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0002_remove_machine_maintenancedate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
