# Generated by Django 4.1.7 on 2023-05-29 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0003_alter_machine_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 29, 9, 42, 34, 970972)
            ),
        ),
    ]
