# Generated by Django 4.1.7 on 2023-05-29 09:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0004_alter_machine_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 29, 9, 49, 31, 698022)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="telephone",
            field=models.CharField(
                default="None",
                max_length=10,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
