# Generated by Django 4.1.7 on 2023-05-03 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0004_alter_personnel_n_secu"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mach",
            field=models.CharField(
                choices=[
                    ("PC", "PC - Run windows"),
                    ("Mac", "MAC - Run MacOS"),
                    ("Serveur", "Serveur - Simple Server to deploy virtual machines"),
                    ("Switch", "Switch - Tom maintains and connect servers "),
                ],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 3, 7, 53, 57, 659866)
            ),
        ),
    ]
