# Generated by Django 4.1.7 on 2023-05-14 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0005_alter_machine_maintenancedate_alter_machine_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 14, 14, 5, 13, 756015)
            ),
        ),
    ]
