# Generated by Django 4.1.7 on 2023-05-14 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0006_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 14, 14, 7, 39, 879355)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Homme", "Monsieur"),
                    ("Femme", "Madame"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=32,
            ),
        ),
    ]
