# Generated by Django 4.1.7 on 2023-05-13 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0009_alter_machine_maintenancedate_alter_personnel_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 13, 7, 48, 45, 934347)
            ),
        ),
    ]
