# Generated by Django 4.1.7 on 2023-05-29 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0009_alter_infrastructure_administrateur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="administrateur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("role", "Administrateur"), ("site", models.F("site"))
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrateur_infrastructure",
                to="computerApp.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 29, 15, 42, 38, 753158)
            ),
        ),
    ]
