# Generated by Django 4.1.7 on 2023-06-03 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0010_alter_infrastructure_administrateur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 3, 10, 3, 2, 160940)
            ),
        ),
    ]
