# Generated by Django 4.1.7 on 2023-05-14 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0010_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 14, 15, 42, 14, 442487)
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="genre",
            field=models.CharField(
                choices=[("Monsieur", "Homme"), ("Madame", "Femme"), ("", "Autre")],
                default="Autre",
                max_length=32,
            ),
        ),
    ]
