# Generated by Django 4.1.7 on 2023-06-03 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0012_alter_machine_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructure",
            name="machines",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(("site", models.F("site"))),
                related_name="infrastructures",
                to="computerApp.machine",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 3, 11, 28, 57, 25793)
            ),
        ),
    ]
