# Generated by Django 4.1.7 on 2023-05-04 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0012_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personnel",
            old_name="N_secu",
            new_name="secu",
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 4, 8, 21, 2, 276704)
            ),
        ),
    ]
