# Generated by Django 4.1.7 on 2023-05-14 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0012_alter_machine_maintenancedate_alter_personnel_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="site",
            field=models.CharField(
                choices=[("Tours", "Tours"), ("Paris", "Paris")],
                default="Paris",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 14, 15, 51, 27, 939076)
            ),
        ),
    ]
