# Generated by Django 4.1.7 on 2023-05-04 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0013_rename_n_secu_personnel_secu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 4, 8, 55, 26, 423338)
            ),
        ),
    ]
