# Generated by Django 4.1.7 on 2023-05-14 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0013_machine_site_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="administrateur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("role", "Administrateur"),
                    ("site", django.db.models.expressions.OuterRef("site")),
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines_administrees",
                to="computerApp.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 14, 16, 27, 50, 672929)
            ),
        ),
    ]
