# Generated by Django 4.1.7 on 2023-05-13 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0013_alter_machine_maintenancedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="site",
            field=models.CharField(
                choices=[("Tours", "Tours"), ("Paris", "Paris")],
                default="Paris",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 13, 15, 49, 43, 623878)
            ),
        ),
    ]
