# Generated by Django 4.1.7 on 2023-05-14 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0015_alter_machine_administrateur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 14, 16, 50, 48, 731876)
            ),
        ),
    ]
