# Generated by Django 4.1.7 on 2023-05-15 21:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("computerApp", "0020_alter_machine_administrateur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="administrateur",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to="get_administrateur_choices",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrateur_machines",
                to="computerApp.personnel",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="maintenanceDate",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 15, 21, 18, 25, 516877)
            ),
        ),
    ]
